USE EAT_SCHOOL_LUNCH;
DROP TABLE IF EXISTS GEN_PROPS;
CREATE TABLE GEN_PROPS (
    ID          INTEGER NOT NULL auto_increment PRIMARY KEY,
    KEY_NAME    VARCHAR(50),
    KEY_VALUE   VARCHAR(50),
    DESCRIPTION VARCHAR(100)
);
COMMIT;