USE EAT_SCHOOL_LUNCH;
DROP TABLE IF EXISTS COUNTRIES;
CREATE TABLE COUNTRIES (
    ID          INTEGER NOT NULL auto_increment PRIMARY KEY,
    DESCRIPTION VARCHAR(4000),
    CODE        VARCHAR(10)
);

INSERT INTO COUNTRIES (DESCRIPTION, CODE) VALUES ("United States", "US");