USE EAT_SCHOOL_LUNCH;
DROP TABLE IF EXISTS COUNTRIES_REGIONS;
CREATE TABLE COUNTRIES_REGIONS (
    ID          INTEGER NOT NULL auto_increment PRIMARY KEY,
    COUNTRY_ID  INTEGER,
    REGION_ID   INTEGER
--     FOREIGN KEY (COUNTRY_ID) REFERENCES COUNTRIES(ID),
--     FOREIGN KEY (REGION_ID) REFERENCES REGIONS(ID)
);

INSERT INTO COUNTRIES_REGIONS (COUNTRY_ID, REGION_ID) SELECT COUNTRIES.ID, REGIONS.ID FROM
COUNTRIES, REGIONS WHERE COUNTRIES.DESCRIPTION='United States' and REGIONS.DESCRIPTION='Alabama';

INSERT INTO COUNTRIES_REGIONS (COUNTRY_ID, REGION_ID) SELECT COUNTRIES.ID, REGIONS.ID FROM
COUNTRIES, REGIONS WHERE COUNTRIES.DESCRIPTION='United States' and REGIONS.DESCRIPTION='Alaska';

INSERT INTO COUNTRIES_REGIONS (COUNTRY_ID, REGION_ID) SELECT COUNTRIES.ID, REGIONS.ID FROM
COUNTRIES, REGIONS WHERE COUNTRIES.DESCRIPTION='United States' and REGIONS.DESCRIPTION='American Samoa';

INSERT INTO COUNTRIES_REGIONS (COUNTRY_ID, REGION_ID) SELECT COUNTRIES.ID, REGIONS.ID FROM
COUNTRIES, REGIONS WHERE COUNTRIES.DESCRIPTION='United States' and REGIONS.DESCRIPTION='Arizona';

INSERT INTO COUNTRIES_REGIONS (COUNTRY_ID, REGION_ID) SELECT COUNTRIES.ID, REGIONS.ID FROM
COUNTRIES, REGIONS WHERE COUNTRIES.DESCRIPTION='United States' and REGIONS.DESCRIPTION='California';

INSERT INTO COUNTRIES_REGIONS (COUNTRY_ID, REGION_ID) SELECT COUNTRIES.ID, REGIONS.ID FROM
COUNTRIES, REGIONS WHERE COUNTRIES.DESCRIPTION='United States' and REGIONS.DESCRIPTION='Colorado';

INSERT INTO COUNTRIES_REGIONS (COUNTRY_ID, REGION_ID) SELECT COUNTRIES.ID, REGIONS.ID FROM
COUNTRIES, REGIONS WHERE COUNTRIES.DESCRIPTION='United States' and REGIONS.DESCRIPTION='Connecticut';

INSERT INTO COUNTRIES_REGIONS (COUNTRY_ID, REGION_ID) SELECT COUNTRIES.ID, REGIONS.ID FROM
COUNTRIES, REGIONS WHERE COUNTRIES.DESCRIPTION='United States' and REGIONS.DESCRIPTION='Delaware';

INSERT INTO COUNTRIES_REGIONS (COUNTRY_ID, REGION_ID) SELECT COUNTRIES.ID, REGIONS.ID FROM
COUNTRIES, REGIONS WHERE COUNTRIES.DESCRIPTION='United States' and REGIONS.DESCRIPTION='District of Columbia';

INSERT INTO COUNTRIES_REGIONS (COUNTRY_ID, REGION_ID) SELECT COUNTRIES.ID, REGIONS.ID FROM
COUNTRIES, REGIONS WHERE COUNTRIES.DESCRIPTION='United States' and REGIONS.DESCRIPTION='Florida';

INSERT INTO COUNTRIES_REGIONS (COUNTRY_ID, REGION_ID) SELECT COUNTRIES.ID, REGIONS.ID FROM
COUNTRIES, REGIONS WHERE COUNTRIES.DESCRIPTION='United States' and REGIONS.DESCRIPTION='Georgia';

INSERT INTO COUNTRIES_REGIONS (COUNTRY_ID, REGION_ID) SELECT COUNTRIES.ID, REGIONS.ID FROM
COUNTRIES, REGIONS WHERE COUNTRIES.DESCRIPTION='United States' and REGIONS.DESCRIPTION='Guam';

INSERT INTO COUNTRIES_REGIONS (COUNTRY_ID, REGION_ID) SELECT COUNTRIES.ID, REGIONS.ID FROM
COUNTRIES, REGIONS WHERE COUNTRIES.DESCRIPTION='United States' and REGIONS.DESCRIPTION='Hawaii';

INSERT INTO COUNTRIES_REGIONS (COUNTRY_ID, REGION_ID) SELECT COUNTRIES.ID, REGIONS.ID FROM
COUNTRIES, REGIONS WHERE COUNTRIES.DESCRIPTION='United States' and REGIONS.DESCRIPTION='Idaho';

INSERT INTO COUNTRIES_REGIONS (COUNTRY_ID, REGION_ID) SELECT COUNTRIES.ID, REGIONS.ID FROM
COUNTRIES, REGIONS WHERE COUNTRIES.DESCRIPTION='United States' and REGIONS.DESCRIPTION='Illinois';

INSERT INTO COUNTRIES_REGIONS (COUNTRY_ID, REGION_ID) SELECT COUNTRIES.ID, REGIONS.ID FROM
COUNTRIES, REGIONS WHERE COUNTRIES.DESCRIPTION='United States' and REGIONS.DESCRIPTION='Indiana';

INSERT INTO COUNTRIES_REGIONS (COUNTRY_ID, REGION_ID) SELECT COUNTRIES.ID, REGIONS.ID FROM
COUNTRIES, REGIONS WHERE COUNTRIES.DESCRIPTION='United States' and REGIONS.DESCRIPTION='Iowa';

INSERT INTO COUNTRIES_REGIONS (COUNTRY_ID, REGION_ID) SELECT COUNTRIES.ID, REGIONS.ID FROM
COUNTRIES, REGIONS WHERE COUNTRIES.DESCRIPTION='United States' and REGIONS.DESCRIPTION='Kansas';

INSERT INTO COUNTRIES_REGIONS (COUNTRY_ID, REGION_ID) SELECT COUNTRIES.ID, REGIONS.ID FROM
COUNTRIES, REGIONS WHERE COUNTRIES.DESCRIPTION='United States' and REGIONS.DESCRIPTION='Kentucky';

INSERT INTO COUNTRIES_REGIONS (COUNTRY_ID, REGION_ID) SELECT COUNTRIES.ID, REGIONS.ID FROM
COUNTRIES, REGIONS WHERE COUNTRIES.DESCRIPTION='United States' and REGIONS.DESCRIPTION='Louisiana';

INSERT INTO COUNTRIES_REGIONS (COUNTRY_ID, REGION_ID) SELECT COUNTRIES.ID, REGIONS.ID FROM
COUNTRIES, REGIONS WHERE COUNTRIES.DESCRIPTION='United States' and REGIONS.DESCRIPTION='Maine';

INSERT INTO COUNTRIES_REGIONS (COUNTRY_ID, REGION_ID) SELECT COUNTRIES.ID, REGIONS.ID FROM
COUNTRIES, REGIONS WHERE COUNTRIES.DESCRIPTION='United States' and REGIONS.DESCRIPTION='Maryland';

INSERT INTO COUNTRIES_REGIONS (COUNTRY_ID, REGION_ID) SELECT COUNTRIES.ID, REGIONS.ID FROM
COUNTRIES, REGIONS WHERE COUNTRIES.DESCRIPTION='United States' and REGIONS.DESCRIPTION='Massachusetts';

INSERT INTO COUNTRIES_REGIONS (COUNTRY_ID, REGION_ID) SELECT COUNTRIES.ID, REGIONS.ID FROM
COUNTRIES, REGIONS WHERE COUNTRIES.DESCRIPTION='United States' and REGIONS.DESCRIPTION='Michigan';

INSERT INTO COUNTRIES_REGIONS (COUNTRY_ID, REGION_ID) SELECT COUNTRIES.ID, REGIONS.ID FROM
COUNTRIES, REGIONS WHERE COUNTRIES.DESCRIPTION='United States' and REGIONS.DESCRIPTION='Minnesota';

INSERT INTO COUNTRIES_REGIONS (COUNTRY_ID, REGION_ID) SELECT COUNTRIES.ID, REGIONS.ID FROM
COUNTRIES, REGIONS WHERE COUNTRIES.DESCRIPTION='United States' and REGIONS.DESCRIPTION='Mississippi';

INSERT INTO COUNTRIES_REGIONS (COUNTRY_ID, REGION_ID) SELECT COUNTRIES.ID, REGIONS.ID FROM
COUNTRIES, REGIONS WHERE COUNTRIES.DESCRIPTION='United States' and REGIONS.DESCRIPTION='Missouri';

INSERT INTO COUNTRIES_REGIONS (COUNTRY_ID, REGION_ID) SELECT COUNTRIES.ID, REGIONS.ID FROM
COUNTRIES, REGIONS WHERE COUNTRIES.DESCRIPTION='United States' and REGIONS.DESCRIPTION='Montana';

INSERT INTO COUNTRIES_REGIONS (COUNTRY_ID, REGION_ID) SELECT COUNTRIES.ID, REGIONS.ID FROM
COUNTRIES, REGIONS WHERE COUNTRIES.DESCRIPTION='United States' and REGIONS.DESCRIPTION='Nebraska';

INSERT INTO COUNTRIES_REGIONS (COUNTRY_ID, REGION_ID) SELECT COUNTRIES.ID, REGIONS.ID FROM
COUNTRIES, REGIONS WHERE COUNTRIES.DESCRIPTION='United States' and REGIONS.DESCRIPTION='Nevada';

INSERT INTO COUNTRIES_REGIONS (COUNTRY_ID, REGION_ID) SELECT COUNTRIES.ID, REGIONS.ID FROM
COUNTRIES, REGIONS WHERE COUNTRIES.DESCRIPTION='United States' and REGIONS.DESCRIPTION='New Hampshire';

INSERT INTO COUNTRIES_REGIONS (COUNTRY_ID, REGION_ID) SELECT COUNTRIES.ID, REGIONS.ID FROM
COUNTRIES, REGIONS WHERE COUNTRIES.DESCRIPTION='United States' and REGIONS.DESCRIPTION='New Jersey';

INSERT INTO COUNTRIES_REGIONS (COUNTRY_ID, REGION_ID) SELECT COUNTRIES.ID, REGIONS.ID FROM
COUNTRIES, REGIONS WHERE COUNTRIES.DESCRIPTION='United States' and REGIONS.DESCRIPTION='New Mexico';

INSERT INTO COUNTRIES_REGIONS (COUNTRY_ID, REGION_ID) SELECT COUNTRIES.ID, REGIONS.ID FROM
COUNTRIES, REGIONS WHERE COUNTRIES.DESCRIPTION='United States' and REGIONS.DESCRIPTION='New York';

INSERT INTO COUNTRIES_REGIONS (COUNTRY_ID, REGION_ID) SELECT COUNTRIES.ID, REGIONS.ID FROM
COUNTRIES, REGIONS WHERE COUNTRIES.DESCRIPTION='United States' and REGIONS.DESCRIPTION='North Carolina';

INSERT INTO COUNTRIES_REGIONS (COUNTRY_ID, REGION_ID) SELECT COUNTRIES.ID, REGIONS.ID FROM
COUNTRIES, REGIONS WHERE COUNTRIES.DESCRIPTION='United States' and REGIONS.DESCRIPTION='North Dakota';

INSERT INTO COUNTRIES_REGIONS (COUNTRY_ID, REGION_ID) SELECT COUNTRIES.ID, REGIONS.ID FROM
COUNTRIES, REGIONS WHERE COUNTRIES.DESCRIPTION='United States' and REGIONS.DESCRIPTION='Northern Marianas Islands';

INSERT INTO COUNTRIES_REGIONS (COUNTRY_ID, REGION_ID) SELECT COUNTRIES.ID, REGIONS.ID FROM
COUNTRIES, REGIONS WHERE COUNTRIES.DESCRIPTION='United States' and REGIONS.DESCRIPTION='Ohio';

INSERT INTO COUNTRIES_REGIONS (COUNTRY_ID, REGION_ID) SELECT COUNTRIES.ID, REGIONS.ID FROM
COUNTRIES, REGIONS WHERE COUNTRIES.DESCRIPTION='United States' and REGIONS.DESCRIPTION='Oklahoma';

INSERT INTO COUNTRIES_REGIONS (COUNTRY_ID, REGION_ID) SELECT COUNTRIES.ID, REGIONS.ID FROM
COUNTRIES, REGIONS WHERE COUNTRIES.DESCRIPTION='United States' and REGIONS.DESCRIPTION='Oregon';

INSERT INTO COUNTRIES_REGIONS (COUNTRY_ID, REGION_ID) SELECT COUNTRIES.ID, REGIONS.ID FROM
COUNTRIES, REGIONS WHERE COUNTRIES.DESCRIPTION='United States' and REGIONS.DESCRIPTION='Pennsylvania';

INSERT INTO COUNTRIES_REGIONS (COUNTRY_ID, REGION_ID) SELECT COUNTRIES.ID, REGIONS.ID FROM
COUNTRIES, REGIONS WHERE COUNTRIES.DESCRIPTION='United States' and REGIONS.DESCRIPTION='Puerto Rico';

INSERT INTO COUNTRIES_REGIONS (COUNTRY_ID, REGION_ID) SELECT COUNTRIES.ID, REGIONS.ID FROM
COUNTRIES, REGIONS WHERE COUNTRIES.DESCRIPTION='United States' and REGIONS.DESCRIPTION='Rhode Island';

INSERT INTO COUNTRIES_REGIONS (COUNTRY_ID, REGION_ID) SELECT COUNTRIES.ID, REGIONS.ID FROM
COUNTRIES, REGIONS WHERE COUNTRIES.DESCRIPTION='United States' and REGIONS.DESCRIPTION='South Carolina';

INSERT INTO COUNTRIES_REGIONS (COUNTRY_ID, REGION_ID) SELECT COUNTRIES.ID, REGIONS.ID FROM
COUNTRIES, REGIONS WHERE COUNTRIES.DESCRIPTION='United States' and REGIONS.DESCRIPTION='South Dakota';

INSERT INTO COUNTRIES_REGIONS (COUNTRY_ID, REGION_ID) SELECT COUNTRIES.ID, REGIONS.ID FROM
COUNTRIES, REGIONS WHERE COUNTRIES.DESCRIPTION='United States' and REGIONS.DESCRIPTION='Tennessee';

INSERT INTO COUNTRIES_REGIONS (COUNTRY_ID, REGION_ID) SELECT COUNTRIES.ID, REGIONS.ID FROM
COUNTRIES, REGIONS WHERE COUNTRIES.DESCRIPTION='United States' and REGIONS.DESCRIPTION='Texas';

INSERT INTO COUNTRIES_REGIONS (COUNTRY_ID, REGION_ID) SELECT COUNTRIES.ID, REGIONS.ID FROM
COUNTRIES, REGIONS WHERE COUNTRIES.DESCRIPTION='United States' and REGIONS.DESCRIPTION='Utah';

INSERT INTO COUNTRIES_REGIONS (COUNTRY_ID, REGION_ID) SELECT COUNTRIES.ID, REGIONS.ID FROM
COUNTRIES, REGIONS WHERE COUNTRIES.DESCRIPTION='United States' and REGIONS.DESCRIPTION='Vermont';

INSERT INTO COUNTRIES_REGIONS (COUNTRY_ID, REGION_ID) SELECT COUNTRIES.ID, REGIONS.ID FROM
COUNTRIES, REGIONS WHERE COUNTRIES.DESCRIPTION='United States' and REGIONS.DESCRIPTION='Virginia';

INSERT INTO COUNTRIES_REGIONS (COUNTRY_ID, REGION_ID) SELECT COUNTRIES.ID, REGIONS.ID FROM
COUNTRIES, REGIONS WHERE COUNTRIES.DESCRIPTION='United States' and REGIONS.DESCRIPTION='Virgin Islands';

INSERT INTO COUNTRIES_REGIONS (COUNTRY_ID, REGION_ID) SELECT COUNTRIES.ID, REGIONS.ID FROM
COUNTRIES, REGIONS WHERE COUNTRIES.DESCRIPTION='United States' and REGIONS.DESCRIPTION='Washington';

INSERT INTO COUNTRIES_REGIONS (COUNTRY_ID, REGION_ID) SELECT COUNTRIES.ID, REGIONS.ID FROM
COUNTRIES, REGIONS WHERE COUNTRIES.DESCRIPTION='United States' and REGIONS.DESCRIPTION='West Virginia';

INSERT INTO COUNTRIES_REGIONS (COUNTRY_ID, REGION_ID) SELECT COUNTRIES.ID, REGIONS.ID FROM
COUNTRIES, REGIONS WHERE COUNTRIES.DESCRIPTION='United States' and REGIONS.DESCRIPTION='Wisconsin';

INSERT INTO COUNTRIES_REGIONS (COUNTRY_ID, REGION_ID) SELECT COUNTRIES.ID, REGIONS.ID FROM
COUNTRIES, REGIONS WHERE COUNTRIES.DESCRIPTION='United States' and REGIONS.DESCRIPTION='Wyoming';